export const itemOptionKor = {
  reqLEV: 'REQLEV',
  reqSTR: 'REQSTR',
  reqDEX: 'REQDEX',
  reqINT: 'REQINT',
  reqLUK: 'REQLUK',
  incSTR: 'STR',
  incDEX: 'DEX',
  incINT: 'INT',
  incLUK: 'LUK',
  incPAD: '공격력',
  incMAD: '마력',
  incEVA: '회피율',
  incACC: '명중률',
  incPDD: '물리방어력',
  incMDD: '마법방어력',
  incMHP: '최대 체력',
  incSpeed: '이동속도',
  incJump: '점프력',
  tuc: '업그레이드 가능 횟수',
} as const;
