name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - '.editorconfig'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install yarn
        uses: yarn/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Get yarn store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(yarn store path --silent)" >> $GITHUB_ENV

      - name: Setup yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn run build

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Build and Publish Electron App
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 6
          retry_wait_seconds: 15
          retry_on: error
          command: yarn run publish
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
